workflows:
  default-workflow:
    name: Android build

    environment:
      flutter: stable

    scripts:
      - name: Check Flutter version
        script: flutter --version

      - name: Clean project
        script: flutter clean

      - name: Get packages
        script: flutter pub get

      - name: Build APK
        script: flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
